# Generated by Django 4.2.3 on 2023-07-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contctus',
            name='company_name',
            field=models.CharField(default='My Company', max_length=100),
        ),
        migrations.AddField(
            model_name='contctus',
            name='country_name',
            field=models.CharField(default='My Country', max_length=100),
        ),
        migrations.AddField(
            model_name='contctus',
            name='email_address',
            field=models.EmailField(default='myname@mydomain.com', max_length=100),
        ),
        migrations.AddField(
            model_name='contctus',
            name='message_text',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='contctus',
            name='mobile_number',
            field=models.CharField(default='+xx-xxx-xxx-xxxx', max_length=100),
        ),
        migrations.AddField(
            model_name='contctus',
            name='role_choice',
            field=models.CharField(choices=[('importer', 'Importer'), ('distributor', 'Distributor'), ('trader', 'Trader'), ('specialist', 'Specialist'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
