# Generated by Django 4.2.3 on 2023-07-21 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_contact_first_name_alter_contact_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='company_name',
            field=models.CharField(default='Your Company', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='country_name',
            field=models.CharField(default='Your Country', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_address',
            field=models.EmailField(default='YourIde@YourEmailDomain.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile_number',
            field=models.CharField(default='(+xx)-xxx-xxx-xxxx  --> +317846401457', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='send_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 11, 51, 0, 231135)),
        ),
    ]
