# Generated by Django 4.2.3 on 2023-07-21 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_contact_email_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email_address',
            field=models.EmailField(default='Id@Domain.com --> rosa124@gmail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='send_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 11, 55, 37, 566)),
        ),
    ]
