# Generated by Django 4.0 on 2023-08-21 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_contact_message_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Name', max_length=100)),
                ('last_name', models.CharField(default='Familly', max_length=100)),
                ('mobile_number', models.CharField(default='(+xx)-xxx-xxx-xxxx --> +317846401457', max_length=100)),
                ('company_name', models.CharField(default='Your Company', max_length=100)),
                ('country_name', models.CharField(default='Your Country', max_length=100)),
                ('email_address', models.EmailField(default='Id@Domain.com --> rosa124@gmail.com', max_length=100)),
                ('message_text', models.TextField(default='Enter Your Massage Please...', max_length=5000)),
                ('role_choice', models.CharField(choices=[('importer', 'Importer'), ('distributor', 'Distributor'), ('trader', 'Trader'), ('specialist', 'Specialist'), ('Other', 'Other')], default='Other', max_length=100)),
                ('send_date_time', models.DateTimeField(default=datetime.datetime(2023, 8, 21, 8, 55, 50, 937050))),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
